[workspace]
resolver = "2"

members = [
    "axi-dma",
    "axi-ethernet", 
    "driver-test/axinet", 
    "boot", "config", "mem", "console", "langitem", "time", "trap",
]

[profile.release]
lto = true

