[package]
name = "boot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = "0.11.1"
config = { path = "../config" }
sbi-rt = { version = "0.0.3", features = ["legacy"] }
log = "0.4"