[package]
name = "trap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = "0.11.0"
log = "0.4"
rv-plic = { git = "https://github.com/duskmoon314/rv-plic" }
