[package]
name = "axinet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boot = { path = "../../boot"}
mem = { path = "../../mem" } 
console = { path = "../../console" }
langitem = { path = "../../langitem"}
time = { path = "../../time" }
axi-dma = { path = "../../axi-dma" }
axi-ethernet = { path = "../../axi-ethernet" }
trap = { path = "../../trap", optional = true }
ats-intc = { path = "../../ats-intc", optional = true }

log = "0.4"
spin = "0.9"
riscv = "0.11.0"
pnet = { version = "0.34.0", default-features = false }
embassy-net-driver = {version = "0.2.0", optional = true }

[features]

smp = []

simple_poll = []
simple_intr = ["trap"]
simple_atsintc = ["ats-intc", "axi-dma/async"]

bulk_poll = []
bulk_intr = ["trap"]
bulk_atsintc = ["ats-intc", "axi-dma/async"]

default = ["bulk_poll"]